apiVersion: v1
kind: PersistentVolume
metadata:
  name: idm-database-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce  # Change it to One
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 10.0.0.4  # Replace with the NFS server IP
    path: "/mnt/nfs-share"  # NFS shared directory
