apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name jsonld.sensorsreport.com;

        location / {
            root /mnt/www/;
            index index.html;
            expires 30d;  # Cache static content for 30 days
            add_header Cache-Control "public, max-age=2592000";
            autoindex on;             # Enable directory listing
            autoindex_exact_size off;  # Show file sizes in KB/MB instead of bytes
            autoindex_format html;     # Display files in an HTML page
            autoindex_localtime on;    # Use local time instead of UTC
        }
    }
