
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs-storage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  # Allows multiple nodes to access the storage
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 10.0.0.4  # Replace with the NFS server IP
    path: "/mnt/nfs-share/www"  # NFS shared directory

